### ISSUE TITLE
Symboltabelle: Auflösung von Namen in Klassen korrekt?

### ISSUE THREAD

**Issue by cagix** [Compiler-CampusMinden/CB-Vorlesung-Master#140]
Im Skript findet sich für die Auflösung von Namen dieser Code-Schnipsel:

https://github.com/Compiler-CampusMinden/CB-Vorlesung-Master/blob/bc28e7ce1226bf5faaba20ba7acdf574a925b221/lecture/frontend/semantics/symboltables/classes.md?plain=1#L218-L221

Ist dies wirklich korrekt? In der Diskussion zum Beispiel für die Sprechstunde 

```java
    package a.b;

    import u.Y;

    class X extends Y {
        int f(int x) {
            int x,y;
            { int x; x - y + 1; }
            x = y + 1;
        }
    }

    class Z {
        class W extends X {
            int x;
            void foo() { f(34); }
        }
        int x,z;
        int f(int x) {
            int y;
            y = x;
            z = x;
        }
    }
```

kamen Zweifel auf?

**Comment by SebastianSossna** [comment]
Ist das jetzt als Rückfrage gemeint?

@Jerbrich (verlinkt er iwie nicht) hat hier Zweifel angemerkt.

```
       class W extends X {
            int x;
            void foo() { f(34); }
        }
        
```
Ich wage mich mal daran zu behaupten er hätte angemerkt, dass wenn W versucht in foo die Funktion f zu resolven, man eine Parentklasse X hätte und dort dann schauen würde.

Falls X nun wie folgt definiert wäre:
`    class X  {
    }`
Dann hätte man in X die Funktion f nicht gefunden und müsste laut unserer Definition im Enclosing scope schauen.

Was hier beschrieben ist:
`
       # ... or enclosing scope if base class 
       `
und auch für X passiert.

Allerdings haben wir auch gesagt, dass wir im Falle das wir es dort nicht finden, auch im enclosing scope von W schauen müssen:
```
    class Z {
        class W extends X {
            int x;
            void foo() { f(34); }
        }
        int x,z;
        int f(int x) {
            int y;
            y = x;
            z = x;
        }
    }
```
Somit auch in der Klasse Z. Wo wir dann ein f finden würden und dieses benutzen würden.
An dieser Stelle hatte ich angemerkt, dass man doch nie bei nested classes im scope der darüberliegenden class schaut.
@liketechnik hat dann gemeint, dass man dort dann nur nach static elementen schaut und niemand hatte dagegen etwas einzuwenden. Ich habe bisher noch nicht viel mit nested Klassen arbeiten müssen.

Wenn wir nun die funktion f der Klasse Z als static ändern, müsste W die funktion f von Z ausführen beim Aufruf foo.


```
    class Z {
        class W extends X {
            int x;
            void foo() { f(34); }
        }
        int x,z;
        static int f(int x) {
            int y;
            y = x;
            z = x;
        }
    }
    
```

    
 Nun hat @Jerbrich hier genauer noch angemerkt, dass wir im Return sind und daher nicht auf die enclosing scope mehr zugreifen können in einer Nachbehandlung, da wir unseren parent zuvor visiten mussten, denn dieser existiert:
` if parentClazz != None: return parentClazz.resolve(name) `
Wir würden somit in diesem Fall nie in den enclosing scope der Klasse hinein schauen.

## Mögliche Lösung: 
Die Antwort vom resolve überprüfen! und wenn null, dann noch den enclosing scope durch gehen:

```
    # NEW: if not here, check any parent class ...
    if parentClazz is not None: 
        resolved_from_parent = parentClazz.resolve(name)
        # NEW NEW: if in parent class then you got it! otherwise proceed with enclosing scope.
        if resolved_from_parent is not None:
            return resolved_from_parent
     # ... or enclosing scope if base class
     try: return enclosingScope.resolve(name)
     except: return None     # not found
 
```

**Comment by cagix** [comment]
> Ist das jetzt als Rückfrage gemeint?

@SebastianSossna Ich wollte den Punkt von gestern festhalten, bevor das wieder in der Versenkung verschwindet :)  Danke für Deine Gedanken!


1. Wenn ich Funktionen betrachte:

```java
class Y {}

class X extends Y {
    int f(int z) { return z; }
}

class Z {
    int f(int z) { return z; }

    class W extends X {
        int f(int z) { return z; }

        void foo() {
            f(34);
        }
    }
}
```

Beim Aufruf von `f(34)` in `void foo()` versuche ich, in die Funktion in der Klasse (also `Z.W`) aufzulösen. Wenn ich sie dort nicht finde, gehe ich in die Elternklasse von `W`, also `X` (und so weiter). Erst wenn ich die Funktion auf diesem Wege nicht finden kann, suche ich im _enclosing scope_ der Klasse `W`, also in `Z`.


2. Wenn ich Attribute/Variablen betrachte:

```java
class Y {}

class X extends Y {
    int x = 1;
}

class Z {
    int x = 3;

    class W extends X {
        int x = 2;

        void foo() {
            System.out.println(x);
        }
    }
}
```

Auch hier würde ich im `System.out.println(x)` zunächst im _enclosing scope_ suchen, also in der Klasse `W`. Wenn ich dort nicht fündig werde, gehe ich zur Elternklasse (`X`) ... Danach suche ich dann im _enclosing scope_ der Klasse `W`, also in `Z` weiter.


Insofern ist der Code-Schnipsel im Skript nicht ganz korrekt, jedenfalls nicht in Bezug auf die Semantik in Java :)  Dein Code-Vorschlag löst das ein wenig besser auf, aber am Ende gibt es ja eine Exception, wenn das Element nicht gefunden wird - ich glaube, wir brauchen einfach nur eine doppelte `try`/`catch`-Struktur?

```
    # NEW: if not here, check any parent class ...
    try: return parentClazz.resolve(name)
    except: 
        # ... or enclosing scope if base class
        try: return enclosingScope.resolve(name)
        except: return None     # not found
```

@SebastianSossna Was denkst Du?

**Comment by cagix** [comment]
argl. nein, es gibt ja keine exception, sondern ein `none`. also doch mit der extra abfrage.


wenn man beim stil von parr bleibt bzw. bei meiner modellierung in https://github.com/Compiler-CampusMinden/CB-Vorlesung-Master/blob/master/lecture/frontend/semantics/symboltables/scopes.md, dann müsste man das mit einer exception machen:

```
    # NEW: if not here, check any parent class ...
    try: 
        res = parentClazz.resolve(name)
        if res is not None: return res
        else: raise Exception()
    except: 
        # ... or enclosing scope if base class
        try: return enclosingScope.resolve(name)
        except: return None     # not found
```

das ist aber irgendwie super unschön. ich glaube, besser wäre es, in `scopes.md` den code umzuformulieren:

```
class Scope:
    Scope enclosingScope    # None if global (outermost) scope
    Symbol<String, Symbol> symbols

    def resolve(name):
        # do we know "name" here?
        if symbols[name]: return symbols[name]
        # if not here, check any enclosing scope
        if enclosingScope: return enclosingScope.resolve(name)
        else: return None     # not found
```

und dann passend hier bei klassen die erweiterung wie von dir vorgeschlagen:

```
    # NEW: if not here, check any parent class ...
    res = None
    if parentClazz and res = parentClazz.resolve(name): return res
    else: 
        # ... or enclosing scope if base class
        if enclosingScope: return enclosingScope.resolve(name)
        else: return None     # not found
```

**Comment by cagix** [comment]
oder laufzeittechnisch unschön, aber ohne hilfsvariable:

```python
    # NEW: if not here, check any parent class ...
    if parentClazz and res = parentClazz.resolve(name): return parentClazz.resolve(name)
    else: 
        # ... or enclosing scope if base class
        if enclosingScope: return enclosingScope.resolve(name)
        else: return None     # not found
```

**Comment by SebastianSossna** [comment]
Es gibt hier, wie so oft, viele Wege die, nach Rom führen.

Persönlich gesehen, ist mir Laufzeit etwas wichtiger als Speicherbedarf.
Dennoch finde ich es auch wichtig, gut lesbaren Code zu haben.

Im Hinblick darauf, dass dieser Code im Rahmen einer Lehrveranstaltung genutzt wird und demzufolge primär der Veranschaulichung dient, würde ich hier mehr Wert auf die Lesbarkeit geben. Daraus folgt, dass der letzte Codeschnipsel mit dem doppelten Aufruf definitiv der Richtige wäre, mMn.

**Comment by cagix** [comment]
jupp :)  ich denke, für das skript ist die lesbarere variante besser, da das prinzip klarer rüber kommt. plus einen hinweis bzgl. "don't do this at home" ...

wollte vor allem schauen, ob jetzt an alles gedacht ist oder ob noch irgendwelche fälle fehlen.

**Comment by cagix** [comment]
@SebastianSossna danke für die diskussion :) ... das aktualisierte skript lade ich grad hoch.
